name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: jrwrigh/hugo-deploy-gh-pages@fix/missing_go_exec
      env:
        HUGO_VERSION: 0.114.0
        TARGET_REPO: andneo/andneo.github.io
        TOKEN: ${{ secrets.EXAMPLE_TOKEN }}
        CNAME: andneo.github.io
